[package]
name = "agenix"
version = "0.15.0"
edition = "2021"

[dependencies]
age = { version = "0.10", features = ["ssh", "armor"] }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
tempfile = "3.0"
serde_json = "1.0"
atty = "0.2"
